---
# All rights reserved (c) 2020-2024, Vladimir Botka <vbotka@gmail.com>
# Simplified BSD License, https://opensource.org/licenses/BSD-2-Clause

- name: "Al_include_confd_vars_list_plain: Include {{ item | basename }}"
  ansible.builtin.include_vars:
    file: "{{ item }}"
    name: al_local_var

- name: "Al_include_confd_vars_list_plain: Debug al_debug={{ al_debug }}"
  ansible.builtin.debug:
    var: al_local_var
  when: al_debug | bool

- name: "Al_include_confd_vars_list_plain: Add vars to list"
  ansible.builtin.set_fact:
    al_include_confd_vars_list: "{{ al_include_confd_vars_list +
                                    al_local_var | json_query('*') }}"

# EOF
...
